spring:
  datasource:
    username: amigoscode
    password: password
    url: jdbc:postgresql://localhost:5432/serverdb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  port: 8080